### ISSUE TITLE
Bundles vulnerable copy of Expat - please update to 2.2.1

### ISSUE THREAD

**Issue by hartwork** [hmatyschok/MeshBSD#6]
Hi!

This repository [bundles an outdated vulnerable copy of Expat 2.1.0](https://github.com/hmatyschok/MeshBSD/tree/master/src/external/expat/lib). Please update your copy to version 2.2.1 with the latest security fixes. A change log with details is available at https://github.com/libexpat/libexpat/blob/master/expat/Changes . Thank you!

Best

&nbsp;
Sebastian

**Comment by hmatyschok** [comment]
Hi!

Thx for your advice. I'll update copy of expat to next version 2.2.1 in couple of some days.

Best

Henning

**Comment by hartwork** [comment]
Commit SHA1 for reference: 9734a506a2d284433904585b5e8c42df88b7b907
